name: Profile Workflow
on:
  schedule:
    # Runs at 12am IST
    # - cron: '30 18 * * *'
    # Runs every 5min
    - cron: "*/5 * * * *"

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest stackOverflow data"
          max_post_count: 14
          feed_list: "https://stackoverflow.com/feeds/user/8487133"
  github-ativity-update:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
  wake-stats-update:
    name: Update Readme with Waka Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
          GH_TOKEN: ${{ secrets.README_TOKEN }}
          SHOW_LINES_OF_CODE: true
          SHOW_LANGUAGE: true
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_TIMEZONE: false
          SHOW_COMMIT: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_LOC_CHART: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false