name: Profile Workflow
on:
  schedule:
    # Runs at 12am IST
    # - cron: '30 18 * * *'
    # Runs every 5min
    - cron: "*/5 * * * *"

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from StackOverflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          commit_message: "Updated readme with the latest stackOverflow data"
          max_post_count: 14
          feed_list: "https://stackoverflow.com/feeds/user/8487133"
  github-ativity-update:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
  loc-update:
    runs-on: ubuntu-latest
    name: Make LOC Badge
    steps:
      - uses: shadowmoose/GHA-LoC-Badge@1.0.0
        id: badge
        with:
          debug: true
          directory: ./
          badge: ./output/badge.svg
          badge_style: "flat"
          ignore: 'node_modules'